[project]
name = "inventory_manager"                    
version = "0.1.0"                             
description = "Simple inventory management with Product/Inventory classes"  
authors = [{ name = "Aniket Sahu" }]         
readme = "README.md"                         
requires-python = ">=3.10"                    

dependencies = [
    "pydantic>=2.0.0",
    "pytest>=8.0.0",
    "pytest-mock>=3.14.0",
    "pytest-cov>=7.0.0",
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.23.0",
    "SQLAlchemy>=2.0.24,<3.0.0",
    "python-dotenv>=1.0.0",
    "pydantic[email]>=2.9.2",
    "httpx>=0.24.1",
    "werkzeug>=3.0.3",
    "psycopg2-binary>=2.9.9",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart==0.0.21",
    "openai>=1.0.0",
    "langchain>=0.1.0",
    "langchain-openai>=0.1.0",
    "langchain-core==0.1.46",
    "langchain-community==0.0.30",
    "pgvector==0.2.5",
    "sentence-transformers>=2.2.2",
    "ollama>=0.1.7"
]

[project.optional-dependencies]
dev = [
    "ruff>=0.5.0",                            
    "black>=24.0.0",                               
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[tool.ruff]
line-length = 88

[tool.black]
line-length = 88                   