"""initial schema

Revision ID: b0f9db409dab
Revises: 
Create Date: 2026-01-10 22:34:08.089526
"""
# Keep: down_revision = None  (already correct)

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f9db409dab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('warranty_period', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.CheckConstraint("(type != 'book') OR (author IS NOT NULL AND author <> '')", name='ck_book_requires_author'),
    sa.CheckConstraint("(type != 'electronic') OR (warranty_period IS NOT NULL AND warranty_period > 0)", name='ck_electronic_requires_warranty'),
    sa.CheckConstraint("(type != 'food') OR (expiry_date IS NOT NULL)", name='ck_food_requires_expiry_date'),
    sa.CheckConstraint("type IN ('food', 'electronic', 'book')", name='ck_valid_product_type'),
    sa.CheckConstraint('price > 0', name='ck_price_positive'),
    sa.CheckConstraint('quantity >= 0', name='ck_quantity_non_negative'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index('ix_products_type', 'products', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_type', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
