"""
Pydantic schema for chat endpoints.
"""
from pydantic import BaseModel, Field


class ChatResponse(BaseModel):
    """
    Response body for inventory chat endpoint.
    """
    answer: str = Field(
        ...,
        description="Answer generated by the RAG + LLM pipeline",
    )
